url: http://oukavip.com/
baseurl:

# Site settings
title: OUKA
email: catherine@oukavip.com
description: "changzhou,china,ouka,Slow Juicr,juicr,USB,常州市欧卡电器有限公司,欧卡,小家电,榨汁机,慢磨机,原汁机"
keywords: "ouka,Slow Juicr,juicr,USB,常州市欧卡电器有限公司,欧卡,小家电,榨汁机,慢磨机,原汁机"


# Team names, titles and social links
people:
- name: Catherine Zhang
  pic: Catheirne Zhang
  position:
  phone: +86-13961273280
  mail: catherine@oukavip.com
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Michael Wong
  pic: Michael Wong
  position:
  phone: +86-13961273280
  mail: sales@oukavip.com
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Lily Jiang
  pic: Lily Jiang
  position:
  phone: +86-17767265450
  mail: Lily@oukavip.com
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Vivi Deng
  pic: Vivi Deng
  position:
  phone: +86-18015866002
  mail: flora@oukavip.com
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
